apiVersion: batch/v1
kind: Job
metadata:
  name: teachers-migrate-fresh-seed
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: lab_6-teachers-service   # твій образ Laravel-сервісу
          imagePullPolicy: IfNotPresent

          command: ["php", "artisan", "migrate:fresh", "--seed", "--force"]
          env:
            - name: DB_HOST
              value: db-teachers
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: teachers
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: password
      restartPolicy: Never
  backoffLimit: 4
