# 1. Deployment Laravel grades-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grades-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grades
  template:
    metadata:
      labels:
        app: grades
    spec:
      containers:
        - name: grades
          image: lab_6-grades-service   # заміни на свій образ
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: db-grades
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: grades
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: password

---
# 2. Service Laravel grades-service
apiVersion: v1
kind: Service
metadata:
  name: grades-service
spec:
  selector:
    app: grades
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
# 3. Deployment MySQL db-grades
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-grades
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-grades
  template:
    metadata:
      labels:
        app: db-grades
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_DATABASE
              value: grades
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: db-grades-pvc

---
# 4. Service MySQL db-grades
apiVersion: v1
kind: Service
metadata:
  name: db-grades
spec:
  selector:
    app: db-grades
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---
# 5. PVC MySQL db-grades-pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-grades-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
