# 1. Deployment Laravel registrations-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registrations-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registrations
  template:
    metadata:
      labels:
        app: registrations
    spec:
      containers:
        - name: registrations
          image: lab_6-registrations-service  # заміни на свій образ
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: db-registrations
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: registrations
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: password

---
# 2. Service Laravel registrations-service
apiVersion: v1
kind: Service
metadata:
  name: registrations-service
spec:
  selector:
    app: registrations
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
# 3. Deployment MySQL db-registrations
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-registrations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-registrations
  template:
    metadata:
      labels:
        app: db-registrations
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_DATABASE
              value: registrations
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: db-registrations-pvc

---
# 4. Service MySQL db-registrations
apiVersion: v1
kind: Service
metadata:
  name: db-registrations
spec:
  selector:
    app: db-registrations
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---
# 5. PVC MySQL db-registrations-pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-registrations-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
