FROM php:8.3-cli

# Встановлюємо системні залежності
RUN apt-get update && apt-get install -y \
    git zip unzip curl libzip-dev libonig-dev libbrotli-dev libxml2-dev procps \
    && docker-php-ext-install pdo_mysql zip pcntl

# Встановлюємо розширення redis
RUN pecl install redis \
    && docker-php-ext-enable redis  
# Встановлюємо Swoole (через PECL)
RUN pecl install swoole && docker-php-ext-enable swoole

# Встановлюємо Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Робоча директорія
WORKDIR /app

# Копіюємо код
COPY . .

# Копіюємо .env.example як .env
RUN cp .env.example .env
# Встановлюємо залежності
RUN composer install --no-dev --optimize-autoloader

# Генеруємо APP_KEY
RUN php artisan key:generate

# Кешуємо конфіги Laravel
RUN php artisan config:cache \
 && php artisan route:cache \
 && php artisan view:cache

# Відкриваємо порт Octane
EXPOSE 80

# Запускаємо Laravel Octane через Swoole
CMD ["php", "artisan", "octane:start", "--server=swoole", "--host=0.0.0.0", "--port=80"]
